import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import SideNav from '@/components/sideNav/SideNav'
import { CityNameProvider } from '@/context/SearchCityContext'

const roboto = Roboto({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${roboto.className} antialiased`}>
                <CityNameProvider>
                    <SideNav />
                    <main className='w-4/5'>{children}</main>
                </CityNameProvider>
            </body>
        </html>
    )
}
